[package]
name = "papyrus_gateway"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.44" }
base64 = { version = "0.13.0" }
bincode = { version = "1.3.3" }
papyrus_storage = { path = "../papyrus_storage" }
flate2 = "1.0"
futures-util = { version = "0.3.21" }
jsonrpsee = { version = "0.13.1", features = ["full"] }
hex = "0.4.3"
primitive-types = { version = "0.12.1" }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = { version = "1.0.81", features = ["preserve_order"] }
sha3 = "0.10.6"
starknet_api = { git = "https://github.com/Shard-Labs/starknet-api", rev = "9362cb8" }
starknet_client = { path = "../starknet_client" }
thiserror = { version = "1.0.31" }
tokio = { version = "1.18.2", features = ["full","sync"] }
tokio-stream = { version = "0.1.8" }
tracing = { version = "0.1.37" }
url = { version = "2.2.2" }

[dev-dependencies]
assert_matches = { version = "1.5.0" }
hex = { version = "0.4.3" }
jsonschema = { version = "0.16.1" }
papyrus_storage = { path = "../papyrus_storage", features = ["testing"] }
test_utils = { path = "../test_utils" }
starknet_api = { git = "https://github.com/Shard-Labs/starknet-api", features = ["testing"] , rev = "9362cb8" }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = { version = "1.0.81", features = ["preserve_order"] }
web3 = { version = "0.18.0" }
indexmap = { version = "1.9.2", features = ["serde"] }